#.travis.yml

language: node_js
node_js:
  - "10.13.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - tsc

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --message "automated deployment via travis"

notifications:
  email:
    on_failure: change
    on_success: change